### PR TITLE
implement dApp

### PR DESCRIPTION
**Pull request by StevenJNPearce**
Fixes: #1

### CODE REVIEW

**Comment by StevenJNPearce** [comment]
@andytudhope @StatusSceptre Any progress on getting this reviewed?

**Comment by StatusSceptre** [comment]
@andytudhope should be back first of next week to review! Thanks Steven.

**Comment by andytudhope** [comment]
Hey @StevenJNPearce! Thanks for this ❤️ What would you recommend as the best way to test it out?

**Comment by StevenJNPearce** [comment]
> Hey @StevenJNPearce! Thanks for this ❤️ What would you recommend as the best way to test it out?

@andytudhope https://ipfs.infura.io/ipfs/QmchsZURNS162ij5396bNCiWq4puWZQGUS5PfgDd1tUzJs/

<blockquote><div><strong><a href="https://ipfs.infura.io/ipfs/QmchsZURNS162ij5396bNCiWq4puWZQGUS5PfgDd1tUzJs/">Status Channels</a></strong></div></blockquote>

**Comment by StevenJNPearce** [comment]
@andytudhope I've fixed an issue - it wasn't correctly detecting when the app was opened from within status. You can use this link to test now: https://vigorous-bhaskara-367a95.netlify.com/
Infura's IPFS gateway appears to be having some issues.

<blockquote><div><strong><a href="https://vigorous-bhaskara-367a95.netlify.com/">Status Channels</a></strong></div></blockquote>

**Comment by andytudhope** [comment]
OK, so the DApp opens in Status and shows me the required channels, nice! 🎉 However, clicking on them leads me to the right get.status.im link (because this DApp must ideally show and direct from anywhere, not just within Status), but then there is an error when I try to "Open in Status" from that page...

```
Unable to load page
-10
net::ERR_UNKNOWN_URL_SCHEME
```

Maybe @jakubgs, @richard-ramos or @flexsurfer knows more about that and could help with further tests?

**Comment by jakubgs** [comment]
>clicking on them leads me the right get.status.im

That's not what it does for me, it leads me to https://status.im/get_desktop/ instead.
>Maybe @jakubgs or @flexsurfer knows more about that and could help with further tests?

I know pretty much 0 about Dapps. Sorry.

<blockquote><div><strong><a href="https://status.im/get_desktop/">Status, a Mobile Client for Ethereum 2.0</a></strong></div></blockquote>

**Comment by flexsurfer** [comment]
@andytudhope we have an issue for that https://github.com/status-im/status-react/issues/7262

**Comment by StevenJNPearce** [comment]
@andytudhope, did you use the netlify link posted above? It works perfectly for me in Status on Android. Click the channel and it opens in Status immediately.

**Comment by StevenJNPearce** [comment]
@andytudhope What's up? Are you on vacation or something?

**Comment by andytudhope** [comment]
Hey @StevenJNPearce - first off, my apologies. Have been travelling more than expected and was without signal for some parts. This does now work on Android, latest release 👍 

We just need to host it somewhere good. @jakubgs do you think we could set up to serve this from something like https://channels.status.im ? @asemiankevich do you think you could help test on iOS?

**Comment by StatusSceptre** [comment]
Hey @jakubgs @asemiankevich any update here?

**Comment by StatusSceptre** [comment]
Ummm, ok. So, I think we can merge this and at least payout the initial bounty because it works as far as I can test it atm. Whenever Jakub has some time, we can get it up on the correct domain, wdyt @pablanopete? And in parallel, we can begin to look at https://github.com/status-im/status-channels-dapp/issues/3

**Comment by jakubgs** [comment]
Ah, sorry, must have missed this one. What do you need under https://channel.status.im ?

**Comment by andytudhope** [comment]
Hey @jakubgs - could we serve this: https://status-im.github.io/status-channels-dapp/dist/ which is currently being built from the `gh-pages` branch in this repo to https://channels.status.im instead?

**Comment by jakubgs** [comment]
It would be trivial if `gh-pages` contained just the site. Does it have to be in `/dist`?

**Comment by jakubgs** [comment]
You will also need a `CNAME` file in the page root with contents `channels.status.im`

**Comment by andytudhope** [comment]
OK, have pushed just the contents of `dist` and a new `CNAME` file onto that branch 👍

**Comment by jakubgs** [comment]
Seems to be working fine:
https://channels.status.im/

<blockquote><div><strong><a href="https://channels.status.im/">Status Channels</a></strong></div></blockquote>

**Pull request merged**
